<a href="https://colab.research.google.com/github/ketanhdoshi/ml/blob/master/examples/TF_Function_Examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Simple examples of each the commonly use TF functions to understand the calculations they are doing under the covers


Tensorflow functions:
*  nn.conv2d()
*  nn.l2_loss()
*  nn.reduce_mean()
*  nn.dropout()

In [ ]:
import tensorflow as tf

### [Example](https://www.dotnetperls.com/conv2d-tensorflow) to illustrate conv2d

In [ ]:
# The input data (could be an image).
temp = tf.constant([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], tf.float32)
temp2 = tf.reshape(temp, [1, 3, 3, 2])

# A filter (affects the convolution).
#filter = tf.constant([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], tf.float32)
filter = tf.constant([1, 1, 0, 0, 0, 0, 0, 0], tf.float32)
filter2 = tf.reshape(filter, [2, 2, 2, 1])

# Use convolution layer on 4D matrices.
convolution = tf.nn.conv2d(temp2, filter2, [1, 1, 1, 1], padding="VALID")

# Initialize session.
session = tf.Session()
tf.global_variables_initializer()

# Evaluate all our variables.
print("INPUT")
print(session.run(temp2))
print("first sample, first channel")
print(session.run(temp2[0, :, :, 0]))
print("first sample, second channel")
print(session.run(temp2[0, :, :, 1]))
print("FILTER")
print(session.run(filter2))
print("filter first channel")
print(session.run(filter2[:, :, 0, :]))
print("filter second channel")
print(session.run(filter2[:, :, 1, :]))
print("CONVOLUTION")
print(session.run(convolution))


INPUT
[[[[1. 1.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]
first sample, first channel
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
first sample, second channel
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
FILTER
[[[[1.]
   [1.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]]]
filter first channel
[[[1.]
  [0.]]

 [[0.]
  [0.]]]
filter second channel
[[[1.]
  [0.]]

 [[0.]
  [0.]]]
CONVOLUTION
[[[[2.]
   [0.]]

  [[0.]
   [0.]]]]


### Example to understand reshape

In [ ]:
temp = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24], tf.float32)
temp2 = tf.reshape(temp, [1, 2, 3, 4])
print("INPUT")
print(session.run(temp2))
print("first sample, first channel")
print(session.run(temp2[0, :, :, 0]))
print("first sample, second channel")
print(session.run(temp2[0, :, :, 1]))

INPUT
[[[[ 1.  2.  3.  4.]
   [ 5.  6.  7.  8.]
   [ 9. 10. 11. 12.]]

  [[13. 14. 15. 16.]
   [17. 18. 19. 20.]
   [21. 22. 23. 24.]]]]
first sample, first channel
[[ 1.  5.  9.]
 [13. 17. 21.]]
first sample, second channel
[[ 2.  6. 10.]
 [14. 18. 22.]]


### [Example](https://www.dotnetperls.com/stack-tensorflow) to understand stack and unstack

In [ ]:
# Shape is (2, 3)
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])
t3 = tf.constant([[13, 14, 15], [16, 17, 18]])


tstack = tf.stack([t1, t2], axis=1) # Shape is (2, 2, 3)

tstack2 = tf.stack([t1, t2], axis=2) # Shape is (2, 3, 2)

tstack_triple = tf.stack([t1, t2, t3], axis=2) # Shape is (2, 3, 3)

unstack0 = tf.unstack(tstack, axis=0)
unstack1 = tf.unstack(tstack, axis=1)
unstack2 = tf.unstack(tstack, axis=2)

session = tf.Session()

print("STACK Axis 1")
print(session.run(tstack))
print(session.run(tf.shape(tstack)))

print("STACK Axis 2")
print(session.run(tstack2))
print(session.run(tf.shape(tstack2)))

print("STACK Axis triple")
print(session.run(tstack_triple))
print(session.run(tf.shape(tstack_triple)))

print("UNSTACK Axis 0")
print(session.run(unstack0))
print(session.run(tf.shape(unstack0)))

print("UNSTACK Axis 1")
print(session.run(unstack1))
print(session.run(tf.shape(unstack1)))

print("UNSTACK Axis 2")
print(session.run(unstack2))
print(session.run(tf.shape(unstack2)))

STACK Axis 1
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[2 2 3]
STACK Axis 2
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
[2 3 2]
STACK Axis triple
[[[ 1  7 13]
  [ 2  8 14]
  [ 3  9 15]]

 [[ 4 10 16]
  [ 5 11 17]
  [ 6 12 18]]]
[2 3 3]
UNSTACK Axis 0
[array([[1, 2, 3],
       [7, 8, 9]], dtype=int32), array([[ 4,  5,  6],
       [10, 11, 12]], dtype=int32)]
[2 2 3]
UNSTACK Axis 1
[array([[1, 2, 3],
       [4, 5, 6]], dtype=int32), array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)]
[2 2 3]
UNSTACK Axis 2
[array([[ 1,  7],
       [ 4, 10]], dtype=int32), array([[ 2,  8],
       [ 5, 11]], dtype=int32), array([[ 3,  9],
       [ 6, 12]], dtype=int32)]
[3 2 2]


### [Example](https://stackoverflow.com/questions/41534593/why-would-i-ever-use-tf-concat-instead-of-tf-stack) to understand concat

And how it is different from stack

In [ ]:
t1 = tf.constant([[1, 2, 3]])
t2 = tf.constant([[4, 5, 6]])

# Shape is (1, 2, 3)
tstack = tf.stack([t1, t2], axis=1)

# Shape is (1, 6)
tconcat = tf.concat([t1, t2], axis=1)

session = tf.Session()

print("T1")
print(session.run(t1))
print("T2")
print(session.run(t2))
print("STACK")
print(session.run(tstack))
print(session.run(tf.shape(tstack)))
print("CONCAT")
print(session.run(tconcat))
print(session.run(tf.shape(tconcat)))

T1
[[1 2 3]]
T2
[[4 5 6]]
STACK
[[[1 2 3]
  [4 5 6]]]
[1 2 3]
CONCAT
[[1 2 3 4 5 6]]
[1 6]


### [Example](https://www.dotnetperls.com/arg-max-tensorflow) to understand argmax

In [ ]:
values = [10, 0, 30, 40, 50, 60, 3, 1, 2]

# Get the index of the minimum value (which is the value 0).
# ... This occurs at index 1.
min = tf.argmin(values, 0)

# Find maximum.
max = tf.argmax(values, 0)

session = tf.Session()

# Find minimum in vector.
print(session.run(min))
print(session.run(max))

1
5


### [Example](https://www.dotnetperls.com/reduce-sum-tensorflow) to understand reduce_sum

In [ ]:
a = tf.constant([[1, 3], [2, 0], [0, 1]])
# Sum elements from different parts of the array.
# ... With no second argument, everything is summed.
#     Second argument indicates what axis to sum.
b = tf.reduce_sum(a)
c = tf.reduce_sum(a, 0)
d = tf.reduce_sum(a, 1)

# Just for looping.
tensors = [b, c, d]

# Loop over our tensors and run a Session on the graph.
for tensor in tensors:
    result = tf.Session().run(tensor)
    print(result)

7
[3 4]
[4 2 1]


### [Example](https://www.dotnetperls.com/reduce-mean-tensorflow) to illustrate how tf.reduce_mean() works

reduce_mean() takes an array of cost values and reduces it to a single scalar cost number by calculating the average of all the costs.

In [ ]:
a = tf.constant([[100, 110], [10, 20], [1000, 1100]])

# Use reduce_mean to compute the average (mean) across a dimension.
b = tf.reduce_mean(a) # Average of all six values in the 2D array
c = tf.reduce_mean(a, axis=0)  # Average of all the values in a column, one column at a time
d = tf.reduce_mean(a, axis=1)  # Average of all the values in a row, one row at a time

session = tf.Session()

print("INPUT")
print(session.run(a))
print("REDUCE MEAN")
print(session.run(b))
print("REDUCE MEAN AXIS 0")
print(session.run(c))
print("REDUCE MEAN AXIS 1")
print(session.run(d))

INPUT
[[ 100  110]
 [  10   20]
 [1000 1100]]
REDUCE MEAN
390
REDUCE MEAN AXIS 0
[370 410]
REDUCE MEAN AXIS 1
[ 105   15 1050]


### [Example](https://www.quora.com/How-does-one-implement-the-L2-loss-in-tensor-flow) to illustrate how tf.nn.l2_loss() works

It just calculates the sum of squares of all individual elements in tensor irrespective of dimensions. Tensor can be of any dimension 

In [ ]:
# Calculate l2_loss in different ways with the same set of numbers
a = np.array ([1.,2.,-3.,1.,1.,1.])
b = a.reshape (2, 3)

w = tf.constant(a)
l = tf.reduce_sum(tf.square(w)) / 2

w1D = tf.constant(a)
l1D = tf.nn.l2_loss(w1D)

w2D = tf.constant(b)
l2D = tf.nn.l2_loss(w2D)

session = tf.Session()

print("Half of Sum of squares")
print(session.run(l))

print("L2_LOSS 1D")
print(session.run(l1D))

print("L2_LOSS 2D")
print(session.run(l2D))

Half of Sum of squares
8.5
L2_LOSS 1D
8.5
L2_LOSS 2D
8.5


### [Example](https://www.dotnetperls.com/dropout-tensorflow) to illustrate how tf.nn.dropout() works

It randomly sets some proportion of the input elements to 0, based on the keep_prob parameter. The values of the remaining elements are scaled up accordingly by a factor of 1/keep_prob

**Details on the keep_prob parameter** and how it affects which elements are selected, and how their values are scaled up

If you have a large amount of neurons, like 10,000 in a layer, and the **keep_prob** is let's say, 0.3, then 3,000 is the expected value of the number of neurons kept. So it's more or less the same thing to say that a keep_prob of 0.3 means to keep the value of 3,000 randomly chosen ones of the 10,000 neurons. But not exactly, because the actual number might vary a bit from 3,000.

The random decision to drop a neuron or not is recalculated for each invocation of the network, so **you will have a different set of neurons dropped on every iteration**. 

**Scaling** comes into the picture because if you drop a certain number of neurons, then the expected sum of the layer will be reduced. So the remaining ones are multiplied to feed forward the same magnitude of values as they would otherwise.

Let's say the network had n neurons and we applied dropout rate 1/2

Training phase, we would be left with n/2 neurons. So if you were expecting output x with all the neurons, now you will get on x/2. So for every batch, the network weights are trained according to this x/2

Testing/Inference/Validation phase, we dont apply any dropout so the output is x. So, in this case, the output would be with x and not x/2, which would give you the incorrect result. So what you can do is scale it to x/2 during testing.

Rather than the above scaling specific to Testing phase. What Tensorflow's dropout layer does is that whether it is with dropout or without (Training or testing), it scales the output so that the sum is constant.

In [ ]:
x = [1., 2., 1., 4., 1., 2.]

# Compute dropout on our tensor with keep_prob of 0.5
# So, randomly half of the elements will be set to 0 and
# the values of the remaining elements will be doubled ie. set to 1/0.5 = 2
result = tf.nn.dropout(x, 0.5)
session = tf.Session()
print(session.run(result))

[0. 0. 2. 8. 2. 4.]
